### ISSUE TITLE
Noble apt `RepositoryMapping` unsupported

### ISSUE THREAD

**Issue by yanksyoon** [canonical/operator-libs-linux#135]
The RepositoryMapping object in apt lib only reads from "/etc/apt/sources.list" and "/etc/apt/sources.list.d/*.list".

Noble's sources are located at `/etc/apt/sources.list.d/ubuntu.sources`, hence raising `InvalidSourceError`.

**Comment by dimaqq** [comment]
A PR would be very welcome :)

**Comment by yanksyoon** [comment]
@dimaqq out of curiosity, may I ask what team is currently maintaining this repository please?

**Comment by benhoyt** [comment]
Our team has picked up maintenance of this repo. We don't have a ton of cycles to spend on maintenance, but this particular one seems like a significant issue! @james-garner-canonical, getting this charm lib to work on Noble seems like a noble task, so assigning to you -- perhaps you can take a look at this in the next week or two.

**Comment by NucciTheBoss** [comment]
@james-garner-canonical have you had chance to tackle this issue yet? I'm getting ganked by it as the HPC team is upgrading the Slurm charms to Noble so that we can have cool kid dkms modules and fancy new login node daemons.
 
Looking at the required changes, we'll likely need to rework how the sources lists are constructed as Noble uses the [deb822 standard](https://manpages.ubuntu.com/manpages/noble/en/man5/sources.list.5.html), which the apt charm library doesn't support; _it only supports the one-line style format_. The extensions are separated between `.list` and `.sources` respectively, so that could be used as the indicator for which parser should be used.

The parser itself seems pretty simple itself by just iterating the over sources list line by line. `deb822` might be more interesting since the sources are specified in blocks rather than lines.

**Comment by james-garner-canonical** [comment]
Thanks for raising this again @NucciTheBoss, and for the helpful info about the deb822 standard. I'll look into this today
