### ISSUE TITLE
snap cache not populated in the way that the snap lib seems to expect

### ISSUE THREAD

**Issue by pengale** [canonical/operator-libs-linux#34]
When tests/integration/test_snap.py on a 20.04 image, I get a lot of warning messages about the snap cache not being populated. I'd expect those warnings to go away after the first test that uses them.

We should brush up on how snapd currently handles its cache, and ensure that the library (which is based on charmhelpers code) interacts with it appropriately.

**Comment by rwcarlsen** [comment]
It appears that snapd creates that file based on its own internal logic on a relatively infrequent basis.  I haven't been able to figure out any way to force/trigger its creation.  Since it is normal for that file to not be present, I think we should just remove those warnings.

**Comment by pengale** [comment]
Removing the warnings makes sense, I think. It sounds like they don't represent an actual delay in anything happening.

**Comment by rwcarlsen** [comment]
There's definitely nothing on our side that makes it slower.  It may be the case that snapd needs to do some extra internal network business that isn't particularly speedy when that file isn't around, but that's not something we have control over.  The snap people said that they deliberately avoid building/caching that file frequently in order to reduce pressure on the snap repo/server.
